name: Deploy to FTP

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to FTP
      env:
        FTP_SERVER: ftps://waws-prod-ma1-019.ftp.azurewebsites.windows.net  # FTP server address
        FTP_USERNAME: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -c "open -u $FTP_USER,$FTP_PASSWORD $FTP_SERVER && put -O /site/wwwroot"
